[package]
name = "en_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33", features = ["wgpu"] }
bevy-inspector-egui = { version = "0.36", default-features = false }
egui_dock = "0.18"
wgpu = "28"

glam = { version = "0.32", features = ["bytemuck"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "6.0"
libloading = "0.9"
pollster = "0.4"

en_core = { path = "../en_core" }
en_ui = { path = "../en_ui" }