[package]
name = "en_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33", features = ["wgpu"] }
wgpu = "27.0.1"

glam = { version = "0.29", features = ["bytemuck"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
directories = "5.0"
libloading = "0.8"

en_core = { path = "../en_core" }
en_ui = { path = "../en_ui" }

en_runner = { path = "../en_runner"}